### ISSUE TITLE
Race condition when closing the Jack plugin

### ISSUE THREAD

**Issue by jeberger** [alsa-project/alsa-plugins#11]
There is a potential race condition that can cause segmentation faults if the Jack process callback is called between the call to `snd_pcm_jack_stop` and `snd_pcm_jack_hw_free`. This was introduced by revision badd921.

**Comment by perexg** [comment]
Fixed in the above commit. Thank you for your report.

**Comment by jeberger** [comment]
Thanks for the fix, however since the Jack process callback runs in a separate thread, the issue may still occur if `snd_pcm_jack_stop` is called just after `snd_pcm_jack_process` has checked `running` but before it returns. Access to `running` and Jack processing should be protected by a mutex. Here's the patch I was using in the mean time:

[0001-fix-race-condition-on-jack-close.patch.txt](https://github.com/alsa-project/alsa-plugins/files/6646366/0001-fix-race-condition-on-jack-close.patch.txt)

**Comment by perexg** [comment]
Could you create a pull request with your fix ?

**Comment by jeberger** [comment]
Unfortunately I'm behind a company proxy that prevents pushing to Github, I'll see what I can do when I get home.

**Comment by perexg** [comment]
If you like, you can also upload a full 'git format-patch' with the description and signed-off-by, so I can apply it.

**Comment by jeberger** [comment]
Thanks, here it is as a signed off 'git format-patch':
[0001-jack-Make-the-running-state-tracing-code-more-robust.patch.txt](https://github.com/alsa-project/alsa-plugins/files/6647273/0001-jack-Make-the-running-state-tracing-code-more-robust.patch.txt)

**Comment by perexg** [comment]
Applied. Thank you.
